version: '3.8'

services:
  
  mysqldb:
    container_name: db
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      network:
        ipv4_address: 172.24.0.3

  app:
    container_name: web
    depends_on:
      - mysqldb
    build: ./WebApp/backend
    restart: unless-stopped
    env_file: .env
    ports:
      - 3001:3001
    environment:
      - DB_HOST=$DB_HOSTNAME
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true
    volumes:
      - web:/media
    networks:
      network:
        ipv4_address: 172.24.0.2
  
  fake-api:
    container_name: fake-api
    build: ./FastAPI/
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      network:
        ipv4_address: 172.24.0.5

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    ports:
      - 3002:3002
    environment:
      - UPTIME_KUMA_PORT=3002
      - HOST=172.24.0.4
    volumes:
      - uptime-kuma:/app/data
    networks:
      network:
        ipv4_address: 172.24.0.4

volumes:
  web:
  db:
  uptime-kuma:

networks:
  network:
    driver: bridge
    ipam:
     config:
      - subnet: 172.24.0.0/16
        gateway: 172.24.0.1


