name: User Story
description: Création d'une user story
title: "[US]: <Titre>"
labels: ["User Story"]
body:
  - type: markdown
    attributes:
      value: |
        Formulaire de création d'une User Story
  - type: textarea #User Story
    id: userstory
    attributes:
      label: User Story
      placeholder: En tant qu'administrateur, je veux pouvoir supprimer tous les utilisateurs afin de semer le chaos.
      value: |
        En tant que <rôle>, je veux pouvoir <fonctionnalité> afin de <cause> .
    validations:
      required: true
  - type: textarea # Description de la User Story
    id: description
    attributes:
      label: Description de la User Story
      description: Explique brievement la User Story
    validations:
      required: true
  - type: textarea # Maquette
    id: maquette
    attributes:
      label: "Maquette"
      description: Optionnel, ajoute les maquettes de la User Story.
      placeholder: Glisser et déposer les photos ici.
    validations:
      required: false
  - type: textarea # Critères d'acceptation 
    id: criteresacceptation
    attributes:
      label: Critères d'acceptation
      description: Veuillez lister tous les critères d'acceptation.
  - type: markdown # Analyse Technique 
    attributes:
      value: Analyse Technique
  - type: textarea # Prérequis
    id: prerequis
    attributes:
      label: Prérequis
  - type: textarea # Impact sur la DB
    id: impactdb
    attributes:
      label: Impact sur la DB

