name: User Story
description: Creating a user story
title: "[US]: <Title>"
labels: ["User Story"]
body:
  - type: markdown
    attributes:
      value: |
        User story creation form
  - type: textarea #User Story
    id: userstory
    attributes:
      label: User Story
      placeholder: As an <actor>, I want to <feature> so that <goal>.
      value: |
        As a <role>, I want to <feature> so that <cause>.
    validations:
      required: true
  - type: textarea #User story description
    id: description
    attributes:
      label: User Story description
      description: Briefly explain the user story
    validations:
      required: true
  - type: textarea #Mockup
    id: mockup
    attributes:
      label: Mockup
      description: Optional, add mockups of the user story.
      placeholder: Drag and drop photos here.
    validations:
      required: false
  - type: textarea #Acceptance criteria
    id: acceptancecriteria
    attributes:
      label: Acceptance Criteria
      description: Please list all acceptance criteria.
  - type: markdown #Technical Analysis
    attributes:
      value: Technical Analysis
  - type: textarea #Prerequisites
    id: prerequis
    attributes:
      label: Prerequisites
  - type: textarea # Database Impact
    id: impactdb
    attributes:
      label: Database Impact

