name: Code Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  frontend_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: ${{github.workspace}}/Web App/frontend/package-lock.json
    - run: npm i
      working-directory: Web App/frontend/
    - run: npm test
      working-directory: Web App/frontend/

  
  backend_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: ${{github.workspace}}/Web App/backend/package-lock.json
    - run: npm i
      working-directory: Web App/backend/
    - run: npm test --if-present #--if-present to delete
      working-directory: Web App/backend/