name: Production Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Clean install dependencies and build frontend
      run: |
        npm ci --legacy-peer-deps
        npm run build-prod
      working-directory: WebApp/frontend/

    - name: Remove test build from backend
      run: rm -rf build
      working-directory: WebApp/backend/

    - name: Move frontend build to backend
      run: mv frontend/build backend/build
      working-directory: WebApp/

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: WebApp/backend/test/, WebApp/frontend/, WebApp/.gitignore, WebApp/package.json, WebApp/package-lock.json, .git, .github, docs, LICENCE.txt, README.md, pre-commit
          SCRIPT_AFTER: |
            cd /home/ubuntu/pvonweb
            sudo docker compose --env-file .env.production down
            sudo docker compose --env-file .env.production build
            sudo docker compose --env-file .env.production up -d
            sudo docker system prune -f
