name: Production Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    frontend-deploy:
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      steps:
          - uses: actions/checkout@v3

          - name: Install dependencies
            run: npm ci --legacy-peer-deps
            working-directory: Web App/frontend/

          - name: Build
            run: npm run build-prod
            working-directory: Web App/frontend/

          - name: Deploy
            uses: reggionick/s3-deploy@v3
            with:
              folder: Web App/frontend/build
              bucket: ${{ secrets.S3_BUCKET }}
              bucket-region: ${{ secrets.S3_BUCKET_REGION }}
              dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
              invalidation: /
              delete-removed: true
              no-cache: true
              private: true
              files-to-include: ".*/*,*/*,**"
