name: Production Deploy

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Npm install and build frontend
      run: |
        npm ci --legacy-peer-deps
        npm run build-prod
      working-directory: Web App/frontend/

    - name: Npm install and build backend
      run: npm ci --legacy-peer-deps
      working-directory: Web App/backend/

    - name: Move frontend build to backend
      run: mv frontend/build backend/build
      working-directory: Web App/

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "Web App/backend/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/, /test/"