name: Production Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Clean install dependencies and build frontend
      run: |
        npm ci --legacy-peer-deps
        npm run build-prod
      working-directory: WebApp/frontend/

    - name: Move frontend build to backend
      run: mv frontend/build backend/build
      working-directory: WebApp/

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "WebApp/backend/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "test/"
          SCRIPT_AFTER: |
            cd /home/ubuntu/pvonweb
            sudo docker system prune -f
            sudo docker compose build
            sudo docker compose up -d
